opcache.validate_timestamps = 0
opcache.file_update_protection = 0
opcache.max_file_size = 0

memory_limit = 512M
max_execution_time = 600
max_input_time = 600
max_input_vars = 5000

upload_max_filesize = 1024M
post_max_size = 1024M
